apiVersion: apps/v1
kind: Deployment
metadata:
  name: quick-links-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quick-links
  template:
    metadata:
      labels:
        app: quick-links
    spec:
      containers:
        - name: quick-links
          image: quick-link-service:latest
          imagePullPolicy: Never
          env:
            - name: DB_HOST
              value: 'postgres-postgresql-ha-pgpool'
            - name: DB_USER
              value: 'postgres'
            - name: DB_PASSWORD
              value: 'password'
            - name: DB_NAME
              value: 'quicklink'
            - name: REDIS_HOST
              value: 'redis-master'
            - name: REDIS_PASSWORD
              value: 'Mx765t6kQe'

---
apiVersion: v1
kind: Service
metadata:
  name: quick-links-service
spec:
  selector:
    app: quick-links
  ports:
    - name: quick-links
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
